" Sample .vimrc managed by dotman.
set nocompatible
syntax on
set number
set ruler
set expandtab
set shiftwidth=2
set tabstop=2
set smartindent
set ignorecase
set smartcase
set incsearch
set hlsearch
set wildmenu
set backspace=indent,eol,start
filetype plugin indent on
